### ISSUE TITLE
sidebar on cs50 home site

### ISSUE THREAD

**Issue by goyalyashpal** [cs50/lectures#11]
### Summary
Make the sidebar of the [cs50/x] course's home website to be collapsable

This is not a super critical issue, but thought to bring this small suggestion in your consideration.

[cs50/x]: https://cs50.harvard.edu/x

### Details:
- Most of the times, I am working in a vertically split layout with cs50/x website on one half, and editor on the other.
- In this layout, the sidebar of the cs50/x site takes up huge space, leaving very little space for the actual content of the page

<p align=center>
<b>Vertically split layout</b>
<br/><br/>
<img src="https://user-images.githubusercontent.com/19423063/215083742-f326d019-15ee-4252-ad68-b33750684161.png" width=600px/>
</p>

### Workarounds considered:

- Browser's reader view: 
- Removing the sidebar from web browser's web inspector tool:

These both workarounds not suitable as these are:
- **Browser dependent**, 

- **Repetitive** 
require redoing at every load of a page

- **Reduce** the website's functionality
content got omitted, commands not copyable etc in reader view or sidebar removal respectively in web-dev-tools hack

- At best, are **fiddly**

So, having a built-in functionality to the site would be awesome.

**Comment by goyalyashpal** [comment]
Small note: it would be nice if the sidebar once collapsed, stayed collapse like shown in following 20 sec clip of a website with collapsible sidebar.:


https://user-images.githubusercontent.com/19423063/215089406-747b8f53-feae-4442-91e9-88965254e7df.mp4


https://user-images.githubusercontent.com/19423063/215259600-05b6a76b-2d66-419a-b5cc-5b119bd40054.mp4

**Comment by goyalyashpal** [comment]
this is very similar in spirit to how the site already performs in mobile:


https://user-images.githubusercontent.com/19423063/215259761-1f617844-8bcb-4950-9b26-521135aee91c.mp4

**Comment by goyalyashpal** [comment]
i think this issue is fixed with an MVC - the website now switches to mobile layout in half screen at default zoom level. thanks for it.

**Comment by dmalan** [comment]
Thanks for the detailed suggestion! This actually inspired a lot of thought and tinkering. In the end, we indeed decided on the behavior that you now see, whereby the mobile layout kicks in sooner so that the menu automatically moves to the top in side-by-side layouts. That seemed simpler than adding a manual UI control!

**Comment by goyalyashpal** [comment]
😃
