### ISSUE TITLE
Suggestion for `style50` usage in lectures with `less -r` pager in initial lectures too

### ISSUE THREAD

**Issue by goyalyashpal** [cs50/lectures#13]
### Summary

Show `style50` being used with a pager (like `less`) early on to ease its usage and uplift the UX. 

I have been using this for quite some time now, and style50 becomes just sooooo much more pleasant to use when the output is controlled and scrollable like that.

```console
$ style50 mario.c | less -r
```

the `-r` option here just ensures that the highlight stays there in the paged output as well.

### Background & Details

I have know the ability to pipe (output of) commands to pagers like `less` or `more` on *nix systems, but i didn't made this suggestion earlier risking increased complexity.

But recently did Week 7 SQL, and saw `more` being used there (ref: 2023/22 [Lecture 7: SQL] at 13:45) as:

```console
$ python favorites.py | more
```

... with accompanying phrase being very nice and abstracted "I have paused the output". So, as a pager is already used in the course, I would like to propose that it's usage be shown earlier as well while using `style50` command due to aforementioned reasons.

[Lecture 7: SQL]: https://www.youtube.com/watch?v=zrCLRC3Ci1c&t=825

**Comment by goyalyashpal** [comment]
@dmalan pinging about it before the upcoming lectures of this new session :smiley: 

whatever ur decision is, i respect that :innocent: 
i just want to know ur thoughts

**Comment by dmalan** [comment]
We've actually replaced `style50` with a graphical version now, but will indeed consider for other commands! Thank you!
