### ISSUE TITLE
`503` `LambdaExecutionError from cloudfront` on cdn.cs50.net/

### ISSUE THREAD

**Issue by goyalyashpal** [cs50/lectures#16]
### Summary

* trying to download some non-archive file from https://cdn.cs50.net/2023/fall/ is failing with `503` error
* however, browsing the site itself, and downloading the archive or say zips is working fine.

### System Info:

```console
$ inxi -Sz
System:
  Kernel: 6.6.48 arch: x86_64 bits: 64
  Desktop: Cinnamon v: 6.2.9 Distro: NixOS 24.11 (Vicuna)

```

### Logs or Screenshots et cetera

* Failure on trying to access `volume.c` or `input.wav` via `curl`

    ```console
    $ curl -IL https://cdn.cs50.net/2023/fall/psets/4/volume/volume.c
    HTTP/2 503 
    content-type: text/html
    content-length: 1019
    server: CloudFront
    date: Tue, 10 Sep 2024 10:25:05 GMT
    x-cache: LambdaExecutionError from cloudfront
    via: 1.1 ....cloudfront.net (CloudFront)
    x-amz-cf-pop: DEL51-P3
    alt-svc: h3=":443"; ma=86400
    x-amz-cf-id: _...==


    ```

* Failure on accessing ... in browser:

    <img src="https://github.com/user-attachments/assets/9db8e0de-888c-4f14-9c57-a971ce4ee8df" width=500px />

* Sucess on trying to access `volume.zip`, or the website's page itself:

    ```console
    $ curl -IL https://cdn.cs50.net/2023/fall/psets/4/volume.zip
    HTTP/2 200 
    content-type: application/zip
    content-length: 313630
      ...
    
    
    $ curl -IL https://cdn.cs50.net/2023/fall/psets/4/
    HTTP/2 200 
    content-type: text/html; charset=utf-8
    content-length: 10656
      ...
    server: nginx/1.24.0
    status: 200 OK
      ...

    ```

**Comment by rongxin-liu** [comment]
Thanks for reporting, we have contacted AWS regarding the issue.

**Comment by goyalyashpal** [comment]
hi @rongxin-liu 

thanks for such quick action :smiley: 
can some note about this be added to the " Status Page "  https://cs50.statuspage.io/ ?
* cdn.cs50.net 
* third-party-services: <a href="https://status.aws.amazon.com/">AWS Lambda (us-east-1)</a>

thanks again.

**Comment by dmalan** [comment]
See https://cs50.statuspage.io/incidents/4t4r10gzfjfd!

**Comment by goyalyashpal** [comment]
awesome.  thanks.  :smiley:
