### ISSUE TITLE
speller (python version) ignores a 45-char word when checking

### ISSUE THREAD

**Issue by curiouskiwi** [cs50/lectures#4]
```
 # ignore alphabetical strings too long to be words
if index >= LENGTH:
```

If the text contains `pneumonoultramicroscopicsilicovolcanoconiosis`, index will be 45 (`LENGTH`) after reading the final `'s'` and the word is thrown away.

If you run `./speller large large` you will see:

```
WORDS MISSPELLED:     0
WORDS IN DICTIONARY:  143091
WORDS IN TEXT:        143090   <<---- missing the longest word
```

**Comment by dmalan** [comment]
Thanks, good catch! https://github.com/cs50/lectures/commit/ef67424ce7452772c4bc07569b4fc95188c41d03
